### ISSUE TITLE
support for promises returned by replacer()

### ISSUE THREAD

**Issue by jankuca** [Faleij/json-stream-stringify#1]
It would be great if it was possible to return a `Promise` from the replacer function.

```javascript
JSONStreamStringify(1, function (key, value) {
  return new Promise((resolve) => {
    resolve(2)
  })
})
```

Currently, the `RecursiveIterable` drops the returned promise as if it were `undefined`.

**Comment by Faleij** [comment]
I agree, it would be great. I will look into it this weekend.

**Comment by jankuca** [comment]
Actually looks like I was mistaken. Promises returned from replacers work just fine.

The issue I was having turned out to be an infinite recursion. The replacer always returned a promise which was turning the result of one promise into a new promise:

```
Promise(2) => 2 => Promise(2) => 2 => …
```

What has to be done to prevent this is creating a promise conditionally.

```javascript
JSONStreamStringify(1, function (key, value) {
  if (value === 1) {
    return new Promise((resolve) => {
      resolve(2)
    })
  }
  return value
})
```

I believe this is the correct approach as it is probably desirable to also pass the result of a promise into the replacer.
