### ISSUE TITLE
How to test streaming responses in Express.js?

### ISSUE THREAD

**Issue by Envek** [Faleij/json-stream-stringify#15]
Hi! Thank you very much for this library: it works like a charm!

But I can't get my Express.js routing tests to pass after switching to streaming responses. Am I missing something in my setup?

**The problem**

 1. My end-to-end tests doesn't pass anymore (seems like they doesn't wait for all the data)

    ```js
    expect((await request(app).get('/streaming')).body).toEqual({some: 'result'}); // But it gets {} instead of {"some":"result"}
    ```

 2. In logs wrong request runtime is being reported (request took 10 seconds but it says that it took 1 second, and no response body size info present, I suppose that it is time to first results being streamed):

    ```
    without streaming:
    GET /sync 200 14.797 ms - 43
    with streaming (it executes for more than a second and writes the same 43 bytes):
    GET /streaming 200 6.513 ms - -
    ```

**Environment**
Node.js: 12.18.3
express.js: 4.16.4
json-stream-stringify: 2.0.2

**Application code**
```js
router.get('/streaming', async function(request, response, next) {
  const immediate = Promise.resolve("Now");
  const postponed = new Promise((resolve) => setTimeout(() => resolve("or never!"), 1000));
  new JsonStreamStringify({ immediate, postponed }).pipe(response);
});
```

**Test**
```js
describe('GET /straming', () => {
  it('should return response', async () => {
    const res = await request(app).get('/streaming')
    expect(res.body).toEqual({ immediate: 'Now', postponed: 'or never!' });
  });
});
```
I'm using Jest and Supertest.

And it fails:

```
    expect(received).toEqual(expected) // deep equality

    - Expected  - 4
    + Received  + 1

    - Object {
    -   "immediate": "Now",
    -   "postponed": "or never!",
    - }
    + Object {}

      13 |   it('should return response', async () => {
      14 |     const res = await request(app).get('/streaming')
    > 15 |     expect(res.body).toEqual({ immediate: 'Now', postponed: 'or never!' });
         |                      ^
      16 |   });
      17 | });
```

**Example app**
To test and reproduce: https://github.com/Envek/express-streaming-test

Thank you in advance! :pray:

**Comment by Faleij** [comment]
The problem here is that reponse type is not set for the streaming example thus, supertest will not automatically parse the response, leaving an empty body object (should be undefined if you ask me but, that's not a part of the issue here but it adds to the confusion when debugging). If you have a look at res.text in the test you will find the full json response as expected.
If you set the response type to json, supertest will be able to automatically parse it and body wont be an empty object:
```javascript
router.get('/streaming', async function(request, response, next) {
  response.type('json');
  const immediate = Promise.resolve("Now");
  const postponed = new Promise((resolve) => setTimeout(() => resolve("or never!"), 1000));
  new JsonStreamStringify({ immediate, postponed }).pipe(response);
});
```

**Comment by Envek** [comment]
Thank you for quick response! It helped with test failures :tada: 

---

Is there any way to also fix logging by the way?

```
GET /sync 200 1008.596 ms - 43
GET /streaming 200 1.127 ms - -
```
In second case it also should print more than 1 second of time and the same 43 bytes. But this is really minor issue.

**Comment by Faleij** [comment]
Morgan uses content-length header to figure out the size, which can't be set when using streamed json, that is if you don't know the exact size beforehand. If you do know, you can set it manually: res.set({ 'Content-Length': 43 });
There is no way to set the header after you have started piping data to the client,
