### ISSUE TITLE
Transpilation issues

### ISSUE THREAD

**Issue by vojtatranta** [Faleij/json-stream-stringify#2]
This bundle uses ES2015+ but does not transpile itself to the ES5 which makes it difficult to bundle it via bundlers like webpack or browserify - it is common to omit node_modules from parsing with Babel or other transpilers.

I suggest to make a prepublish script which would transpile source to ES5 in /lib/ folder and setting main in package.json to lib/jsonStreamify.js

**Comment by Faleij** [comment]
It's not difficult to include this using webpack and babel, if babel is configured properly with webpack you can include this with:
``const JSONStreamStringify = require('babel!json-stream-stringify');``
even if node_modules is excluded for babel in your webpack loaders config.

**Comment by vojtatranta** [comment]
@Faleij sure but we have combined environment for Node/Electron and you can't to this there.

And still, it is not good idea to supply code that can't be run.

**Comment by Faleij** [comment]
if ``babel!`` won't work for you, you can exclude json-stream-stringify from being excluded by babel in the loader config, e.g. 
```javascript
exclude: /(node_modules\/(?!json-stream-stringify)|bower_components)/,
loader: 'babel-loader',
```

This module can be run and a requirement of Node >4.2.2 is explicitly mentioned in the readme and package.json.
Lots of published npm modules are not transpiled and I don't think it's a good idea to transpile everything on an assumption that people want to run it in a ES5 or older environment.

**Comment by vojtatranta** [comment]
In my opinion, you just make it more difficult for other people to use you module out of the box without troubles. It would be just a single line in package.json to make it work for all the user everytime, in every env.

But I understand this, but still, I'll send a PR.

**Comment by personalnadir** [comment]
For what it's worth I came across this issue because the [json-immutable](https://github.com/avocode/json-immutable) library depends on this, and I'm building using Facebook's [create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). The latter complains about non-ES5 code. I can see your point, but agree with @vojtatranta particularly if json-stream-stringify becomes a dependency in more and more projects.

**Comment by Faleij** [comment]
2.0 released, this should now be solved. See readme for info.
