### ISSUE TITLE
Error on importing with Typescript

### ISSUE THREAD

**Issue by khanguy00** [Faleij/json-stream-stringify#26]
Hi, I use Typescript, the code is similar to

```
import JsonStreamStringify from 'json-stream-stringify';

new JsonStreamStringify(data, undefined, 2);
```

This is the error:

`TypeError: json_stream_stringify_1.default is not a constructor`

Can anyone explain why and how to resolve this?

**Comment by Faleij** [comment]
The new import format in v3 is now ``import { JsonStreamStringify } from 'json-stream-stringify';``, hope this solves it for you.
