### ISSUE TITLE
Critical | Unable to handle blank keys in JSON object

### ISSUE THREAD

**Issue by anmoldeep0123** [Faleij/json-stream-stringify#28]
Please find below the sample JSON object with an empty key

{'': 'data1', 'key1': ''}

function replacer(key, value) {
  if (!key) {
    console.log('YES' , key, value);
  }
  return value;
}

let str = '';
const JsonStreamStringify = require('json-stream-stringify');
const stream = new JsonStreamStringify({'': 'data1', 'key1': ''}, replacer , 0, false);
stream.on('data', (data) => {
  str += data.toString();
});
stream.on('end', function () {
  console.log('PARSING NOW ' , str);
});

On the end event, the output is 
// PARSING NOW  {"data1","key1":""}

Please note the JSON is malformed.

**Comment by anmoldeep0123** [comment]
[repro.txt](https://github.com/Faleij/json-stream-stringify/files/9315727/repro.txt)

**Comment by anmoldeep0123** [comment]
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/7692754/184340140-791b4df1-06a6-4c12-8328-62a3b8307449.png">

**Comment by Faleij** [comment]
Thank you for reporting this issue, this should now be fixed in v3.0.1 and be up shortly on NPM.

**Comment by anmoldeep0123** [comment]
@Faleij  please backport this to  "json-stream-stringify": "^2.0.1", as we are strictly dependent on 2.0.1 and we cannot  upgrade to 3.0.1.
