### ISSUE TITLE
Element in array is not serialized randomly

### ISSUE THREAD

**Issue by nachogiljaldo** [Faleij/json-stream-stringify#43]
I have some code that returns:
```
{
  someProperty: 1,
  items: <a stream in objectMode result of performing a query and transforming its values>
}
```

Randomly, I get things rendered like it follows:
```
{
  "someProperty": 1,
  "items": [
    {"id": 1},
    {"id": 2},
    ,
    {"id": 3},
    ,
    ...
  ]
```

As you see it generates invalid json. I have been trying to debug and understand what is going on. But unfortunately I cannot reproduce and I did not manage to generate a stream of objects that produces this.

**Comment by Faleij** [comment]
Have just released v3.1.6 that will not prefix the output with ",\n${indentation}" if the current push is empty, it's just a workaround and not a complete fix. Without knowing what the source stream actually emits it's practically impossible to debug this. For some reason the read() from your source stream results in empty serialization. Let me know if this workaround works for you.

**Comment by nachogiljaldo** [comment]
@Faleij I used yarn patch to run our component with my proposed solution in https://github.com/Faleij/json-stream-stringify/pull/44 and I have not had the issue for 24h, previously 15-20 times a day. I will wait a few days more, but I believe that is indeed the fix.

**Comment by nachogiljaldo** [comment]
@Faleij I can confirm that with my fix only (i.e. not 3.1.6, just a patch with my fix) we're not seeing any issues anymore.

IIUC your workaround, you skip the \n${indentation} but the element would be skipped too (i.e. it's valid json but not the json it should be).
With my fix it generates valid json and the json you really wanted, so I would suggest that we push forward with my PR (happy to add any changes to it you might see fit).

**Comment by nachogiljaldo** [comment]
Nevermind @Faleij , I see that your changes include my suggestion of awaiting this._read (which as I said works for us). 

Also, interestingly, although I am not 100% sure, we had instances of "frozen pods" that would stop responding to healthchecks and those have stopped happening as well when I deployed my patch version.

Anyway, summarizing, I'm going to try tomorrow with version 3.1.6 to see if it does what I expected (which should be the case because it has the await). If so, I'm happy to consider this closed and I can close the PR I opened if you're not interested on the extra tests (or open a new one just for the tests if you are).

**Comment by nachogiljaldo** [comment]
I'm closing this issue, the suggested fix in https://github.com/Faleij/json-stream-stringify/pull/44 applied in https://github.com/Faleij/json-stream-stringify/commit/3e2202b55fa2f0959df5c1161fc02ff0f4c8e030#diff-e2a524d98985a39fe24d1631bce7832879f6d1a67fd083762781b4f6bbe14524R497 fixed it.
